CREATE DATABASE IF NOT EXISTS spring_jdbc_transactions_prog;
CREATE TABLE spring_jdbc_transactions_prog.DEVELOPERS(
  ID   INT NOT NULL AUTO_INCREMENT,
  NAME VARCHAR(50) NOT NULL,
  SPECIALITY VARCHAR(50) NOT NULL,
  EXPERIENCE INT NOT NULL,
  PRIMARY KEY (ID)
);

CREATE TABLE spring_jdbc_transactions_prog.PROJECTS(
  DEVELOPERS_ID INT NOT NULL,
  NAME  VARCHAR(50) NOT NULL,
  COMPANY VARCHAR(50) NOT NULL
);